### ISSUE TITLE
Could not install demo database

### ISSUE THREAD

**Issue by andersdd** [davidbeauchamp/xtuple-utility#12]
Steps:
Database Maintenance
10. Download Latest Demo Database   (successful)

System then asks whether to deploy this database.  Deployment fails and system exits.  Console output reports:  ERROR:  role "admin" does not exist

Set up password for "admin" but issue persists.

**Comment by davidbeauchamp** [comment]
Was the cluster initialized before trying to load the database to it? I could check for the presence of the admin user before allowing a restore.

**Comment by andersdd** [comment]
Yes - manually initialised a cluster.  And selected that as part of the process

**Comment by davidbeauchamp** [comment]
Closing for now as I have been unable to reproduce it. If a similar error pops up again please file a new ticket.
