### ISSUE TITLE
Error during install_mwc: Fetch Failed xtuple-query-1.0.2.tgz

### ISSUE THREAD

**Issue by paladinlogic** [davidbeauchamp/xtuple-utility#29]
> npm ERR! fetch failed https://registry.npmjs.org/xtuple-query/-/xtuple-query-1.0.2.tgz
> npm WARN optional dep failed, continuing xtuple-query@https://registry.npmjs.org/xtuple-query/-/xtuple-query-1.0.2.tgz

Seems to continue from there.

**Comment by davidbeauchamp** [comment]
This is due to the change of ownership on a published npm module a little while back. We removed that as a module dependency and just include the code with our main codebase. 

That error can be ignored as it doesn't impact the installation, and will be removed soon.
