### ISSUE TITLE
Failed to connect to database

### ISSUE THREAD

**Issue by andersdd** [davidbeauchamp/xtuple-utility#4]
Installing new database (from demo template).

When requested, I name the database something other than the default ("demo").  The install failed due to an inability to connect to the database.  Likely caused by missing pg_hba settings.   

Suggest updating pg_hba after installing a new Db.  Also check for this error and return a meaningful error message.

Creating database demo.
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
Restoring database demo from file /tmp/xtdb/4.8.1-empty.backup on server localhost:5432
pg_restore: [archiver (db)] connection to database "demo" failed: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

**Comment by davidbeauchamp** [comment]
Is that the right server information (localhost/5432)? Is there database information set? (and displayed along the top window title) and is this on a server with existing postgres or one the utility installed. 

Looking into things, it appears its running psql and pg_restore without su'ing to the postgres user first. Should probably make this conform with the other commands.

**Comment by andersdd** [comment]
This occurred running through the utility -> provisioning menu.

Selected installpg93, initdb, demodb. 

postgres installed, looks like initdb ran.   I am not sure but it is possibly related to not creating postgres clusters (?)

**Comment by davidbeauchamp** [comment]
Ahh! Well, installing postgresql pg9.3 removes the default cluster. Guess we need some way to detect if you have chosen one thing that relies on another. installpg93, provisioncluster then initdb (and whatever else). database name doesn't matter but must conform to pg standards of course (ie, no starting with a numeral)
